repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-symlinks
  - id: check-merge-conflict
  - id: check-json
  - id: check-added-large-files
    args: [--maxkb=51200]
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args: [--max-line-length=120]
