# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(611, 324)
        self.graph_raw_dataset = QtWidgets.QGraphicsView(Dialog)
        self.graph_raw_dataset.setGeometry(QtCore.QRect(10, 100, 211, 181))
        self.graph_raw_dataset.setObjectName("graph_raw_dataset")
        self.list_dataset = QtWidgets.QComboBox(Dialog)
        self.list_dataset.setGeometry(QtCore.QRect(10, 30, 211, 31))
        self.list_dataset.setObjectName("list_dataset")
        self.list_dataset.addItem("")
        self.list_dataset.addItem("")
        self.list_dataset.addItem("")
        self.text_raw_dataset = QtWidgets.QTextBrowser(Dialog)
        self.text_raw_dataset.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.text_raw_dataset.setObjectName("text_raw_dataset")
        self.text_choose_dataset = QtWidgets.QTextBrowser(Dialog)
        self.text_choose_dataset.setGeometry(QtCore.QRect(10, 10, 101, 20))
        self.text_choose_dataset.setObjectName("text_choose_dataset")
        self.result_graph_dataset = QtWidgets.QGraphicsView(Dialog)
        self.result_graph_dataset.setGeometry(QtCore.QRect(230, 100, 211, 181))
        self.result_graph_dataset.setObjectName("result_graph_dataset")
        self.result_dataset = QtWidgets.QTextBrowser(Dialog)
        self.result_dataset.setGeometry(QtCore.QRect(230, 80, 101, 20))
        self.result_dataset.setObjectName("result_dataset")
        self.list_algorithm = QtWidgets.QComboBox(Dialog)
        self.list_algorithm.setGeometry(QtCore.QRect(230, 30, 211, 31))
        self.list_algorithm.setObjectName("list_algorithm")
        self.list_algorithm.addItem("")
        self.list_algorithm.addItem("")
        self.list_algorithm.addItem("")
        self.text_choose_algorithm = QtWidgets.QTextBrowser(Dialog)
        self.text_choose_algorithm.setGeometry(QtCore.QRect(230, 10, 101, 20))
        self.text_choose_algorithm.setObjectName("text_choose_algorithm")
        self.log_display = QtWidgets.QTextBrowser(Dialog)
        self.log_display.setGeometry(QtCore.QRect(460, 30, 141, 251))
        self.log_display.setObjectName("log_display")
        self.text_process_log = QtWidgets.QTextBrowser(Dialog)
        self.text_process_log.setGeometry(QtCore.QRect(460, 10, 101, 20))
        self.text_process_log.setObjectName("text_process_log")
        self.button_process = QtWidgets.QPushButton(Dialog)
        self.button_process.setGeometry(QtCore.QRect(10, 290, 75, 23))
        self.button_process.setObjectName("button_process")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "社区发现GUI"))
        self.list_dataset.setItemText(0, _translate("Dialog", "Zachary\'s Karate Club"))
        self.list_dataset.setItemText(1, _translate("Dialog", "Political Books"))
        self.list_dataset.setItemText(2, _translate("Dialog", "American College football"))
        self.text_raw_dataset.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">数据集原始图像</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.text_choose_dataset.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">数据集选择</span></p></body></html>"))
        self.result_dataset.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">社区分类结果</span></p></body></html>"))
        self.list_algorithm.setItemText(0, _translate("Dialog", "Louvain"))
        self.list_algorithm.setItemText(1, _translate("Dialog", "SBM"))
        self.list_algorithm.setItemText(2, _translate("Dialog", "谱聚类"))
        self.text_choose_algorithm.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">算法选择</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.text_process_log.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">运行日志</p></body></html>"))
        self.button_process.setText(_translate("Dialog", "process"))
